import json
import re

# Generate more questions for categories that need them
# OS needs ~173 more, language needs ~161 more

os_extra = []
os_templates = [
    ("Linux中{cmd}命令的作用是什么？", "easy", "{cmd}是Linux常用命令，用于{desc}。常用参数：{params}。"),
    ("什么是{concept}？在操作系统中的作用？", "medium", "{concept}是操作系统中的重要概念。{detail}。它在系统运行中起到{role}的作用。"),
    ("如何排查{problem}问题？", "hard", "排查{problem}的步骤：1.收集信息 2.分析日志 3.定位原因 4.实施修复 5.验证结果。常用工具：{tools}。"),
]

os_data = [
    ("ls", "列出目录内容", "-a显示隐藏 -l详细 -h人类可读 -R递归", "ls命令用于查看目录内容"),
    ("cd", "切换目录", "~家目录 .当前 ..上级 -上一次", "cd命令用于在目录间切换"),
    ("pwd", "显示当前目录", "无参数", "pwd显示当前工作目录的绝对路径"),
    ("mkdir", "创建目录", "-p递归创建 -m设置权限", "mkdir用于创建新目录"),
    ("rm", "删除文件或目录", "-r递归 -f强制 -i交互确认", "rm用于删除文件，-rf组合需谨慎使用"),
    ("cp", "复制文件", "-r递归 -p保留属性 -i覆盖确认", "cp用于复制文件或目录"),
    ("mv", "移动或重命名", "-i覆盖确认 -f强制 -n不覆盖", "mv用于移动文件或重命名"),
    ("cat", "查看文件内容", "-n显示行号 -b非空行号", "cat用于查看完整文件内容"),
    ("grep", "文本搜索", "-i忽略大小写 -r递归 -n行号 -c计数", "grep用于在文件中搜索匹配的行"),
    ("find", "查找文件", "-name按名 -type按类型 -size按大小 -mtime按时间", "find用于在目录树中查找文件"),
    ("awk", "文本处理", "-F分隔符 NR行号 NF字段数", "awk是强大的文本处理工具，支持模式匹配和操作"),
    ("sed", "流编辑器", "-i原地修改 -n静默 -e多命令", "sed用于对文本流进行编辑和转换"),
    ("sort", "排序", "-r逆序 -n数值 -k指定列 -u去重", "sort用于对文本行排序"),
    ("uniq", "去重", "-c计数 -d仅重复 -u仅唯一", "uniq用于去除相邻重复行"),
    ("wc", "统计", "-l行数 -w单词 -c字节", "wc用于统计文件的行数、单词数和字节数"),
    ("head", "查看头部", "-n行数 -c字节数", "head用于查看文件开头部分"),
    ("tail", "查看尾部", "-n行数 -f跟踪 -F重试跟踪", "tail用于查看文件末尾，-f常用于日志跟踪"),
    ("chmod", "修改权限", "u/g/o/a +/-/= r/w/x 或八进制", "chmod用于修改文件权限"),
    ("chown", "修改所有者", "-R递归 user:group", "chown用于修改文件所有者和组"),
    ("ps", "查看进程", "aux全格式 -ef全格式", "ps用于查看当前系统进程状态"),
    ("top", "实时监控", "-d刷新间隔 -p指定PID", "top实时显示进程资源使用情况"),
    ("kill", "发送信号", "-9强制终止 -15优雅终止 -l列出信号", "kill用于向进程发送信号"),
    ("df", "磁盘使用", "-h人类可读 -i inode信息", "df显示文件系统磁盘空间使用情况"),
    ("du", "目录大小", "-h人类可读 -s总计 --max-depth深度", "du显示目录和文件的空间使用"),
    ("free", "内存使用", "-h人类可读 -m MB -g GB", "free显示系统内存使用情况"),
    ("netstat", "网络状态", "-t TCP -u UDP -l监听 -n数字 -p程序", "netstat显示网络连接和监听状态"),
    ("ss", "套接字统计", "-t TCP -u UDP -l监听 -n数字", "ss比netstat更快，显示套接字统计"),
    ("lsof", "打开文件", "-i网络 -p进程 -u用户", "lsof列出进程打开的文件和网络连接"),
    ("tcpdump", "抓包", "-i接口 -w保存 -r读取 -nn不解析", "tcpdump是命令行网络抓包工具"),
    ("strace", "系统调用追踪", "-p PID -e过滤 -f子进程", "strace追踪进程的系统调用"),
    ("ltrace", "库调用追踪", "-p PID -e过滤", "ltrace追踪进程的库函数调用"),
    ("nm", "符号表", "-D动态符号 -g全局 -u未定义", "nm列出目标文件的符号表"),
    ("ldd", "动态依赖", "无参数", "ldd显示程序依赖的共享库"),
    ("objdump", "反汇编", "-d反汇编 -h段头 -x全部头", "objdump显示目标文件信息"),
    ("readelf", "ELF信息", "-h文件头 -S段头 -s符号", "readelf显示ELF文件信息"),
    ("dmesg", "内核日志", "-T时间戳 -l级别 -w跟踪", "dmesg显示内核环形缓冲区日志"),
    ("journalctl", "系统日志", "-u服务 -f跟踪 --since时间", "journalctl查询systemd日志"),
    ("systemctl", "服务管理", "start/stop/restart/status/enable/disable", "systemctl管理systemd服务"),
    ("crontab", "定时任务", "-e编辑 -l列出 -r删除", "crontab管理用户的定时任务"),
    ("tar", "打包压缩", "-c创建 -x解压 -z gzip -j bzip2 -v详细", "tar用于打包和解包文件"),
    ("ssh", "远程连接", "-p端口 -i密钥 -L本地转发 -R远程转发", "ssh用于安全远程登录"),
    ("scp", "远程复制", "-r递归 -P端口 -i密钥", "scp用于远程文件复制"),
    ("rsync", "同步", "-a归档 -v详细 -z压缩 --delete删除", "rsync高效远程文件同步"),
    ("curl", "HTTP请求", "-X方法 -H头 -d数据 -o保存 -s静默", "curl是命令行HTTP客户端"),
    ("wget", "下载", "-c续传 -q静默 -O保存 -r递归", "wget是非交互式下载工具"),
    ("docker", "容器管理", "run/stop/rm/ps/images/build/push", "docker管理容器和镜像"),
    ("kubectl", "K8s管理", "get/describe/apply/delete/logs/exec", "kubectl管理Kubernetes资源"),
    ("iptables", "防火墙", "-A添加 -D删除 -L列出 -F清空", "iptables配置Linux防火墙规则"),
    ("sysctl", "内核参数", "-a列出 -w设置 -p加载", "sysctl查看和修改内核参数"),
    ("ulimit", "资源限制", "-a列出 -n文件数 -u进程数 -m内存", "ulimit设置用户资源限制"),
    ("nice/renice", "进程优先级", "nice值-20到19，值越低优先级越高", "nice设置进程调度优先级"),
    ("nohup", "不挂断运行", "&后台 nohup.out输出", "nohup让命令在终端关闭后继续运行"),
    ("screen/tmux", "终端复用", "new/detach/attach/list", "screen/tmux实现终端会话复用"),
    ("xargs", "参数构建", "-n每行数 -I替换 -P并行 -d分隔符", "xargs将标准输入转为命令参数"),
    ("tee", "分流输出", "-a追加 -i忽略中断", "tee将输出同时送到文件和标准输出"),
    ("tr", "字符转换", "-d删除 -s压缩 -c取反", "tr用于字符替换和删除"),
    ("cut", "字段提取", "-d分隔符 -f字段 -c字符", "cut按列提取文本"),
    ("paste", "合并行", "-d分隔符 -s串行", "paste按行合并多个文件"),
    ("diff", "比较文件", "-u统一格式 -r递归 -q仅报告", "diff比较两个文件的差异"),
    ("patch", "打补丁", "-p剥离层级 -R反向 -d目录", "patch应用diff生成的补丁"),
    ("ln", "链接", "-s软链接 -f强制 -n不覆盖", "ln创建文件链接"),
    ("stat", "文件状态", "-f文件系统 -c格式", "stat显示文件详细状态信息"),
    ("file", "文件类型", "-b简短 -i MIME -z压缩内", "file检测文件类型"),
    ("which/whereis", "命令查找", "which在PATH中查找 whereis查找二进制/源码/手册", "which和whereis用于查找命令位置"),
    ("env/export", "环境变量", "env显示 export设置 unset删除", "env/export管理环境变量"),
    ("umask", "默认权限", "022/027等八进制值", "umask设置新建文件的默认权限掩码"),
    ("chroot", "改变根目录", "需要复制必要文件", "chroot改变进程的根目录，用于隔离环境"),
    ("mount/umount", "挂载", "-t类型 -o选项 -a全部", "mount挂载文件系统，umount卸载"),
    ("fdisk/parted", "磁盘分区", "fdisk MBR分区 parted GPT分区", "fdisk和parted是磁盘分区工具"),
    ("mkfs", "格式化", "-t类型 -c检查", "mkfs在分区上创建文件系统"),
    ("fsck", "文件系统检查", "-y自动修复 -n不修复 -f强制", "fsck检查和修复文件系统"),
    ("dd", "数据复制", "if=输入 of=输出 bs=块大小 count=数量", "dd用于低级数据复制和磁盘操作"),
    ("vmstat", "虚拟内存统计", "1每秒 5每5秒", "vmstat报告虚拟内存统计信息"),
    ("iostat", "IO统计", "-x扩展 -c CPU -d磁盘", "iostat报告CPU和IO统计"),
    ("sar", "系统活动报告", "-u CPU -r内存 -d磁盘 -n网络", "sar收集和报告系统活动信息"),
    ("mpstat", "CPU统计", "-P指定CPU 间隔 次数", "mpstat报告CPU统计信息"),
    ("pidstat", "进程统计", "-u CPU -r内存 -d IO -w上下文", "pidstat报告进程资源使用"),
    ("perf", "性能分析", "stat统计 record记录 report报告", "perf是Linux性能分析框架"),
    ("blktrace", "块IO追踪", "-d设备 -o输出", "blktrace追踪块设备IO请求"),
    ("fio", "IO测试", "--rw读写 --bs块大小 --size大小", "fio是灵活的IO基准测试工具"),
    ("iperf3", "网络性能", "-s服务端 -c客户端 -t时间 -P并行", "iperf3测试网络带宽性能"),
    ("ab", "HTTP压测", "-n请求数 -c并发数 -k keepalive", "ab是Apache HTTP基准测试工具"),
    ("wrk", "HTTP压测", "-t线程 -c连接 -d持续时间", "wrk是现代HTTP基准测试工具"),
    ("sysbench", "系统基准", "--test=cpu/memory/io/threads", "sysbench是多功能系统基准测试工具"),
    ("stress", "压力测试", "--cpu --io --vm --hdd --timeout", "stress对系统施加压力测试"),
    ("nc", "网络工具", "-l监听 -z扫描 -u UDP", "nc是网络瑞士军刀，支持多种网络操作"),
    ("dig", "DNS查询", "+short简短 +trace追踪 @服务器", "dig是DNS查询工具"),
    ("nslookup", "DNS查询", "交互式或非交互式", "nslookup查询DNS记录"),
    ("host", "DNS查询", "-a全部 -t类型", "host简单的DNS查询工具"),
    ("traceroute/mtr", "路由追踪", "-n不解析 -I ICMP -T TCP", "traceroute追踪网络路由路径"),
    ("nmap", "端口扫描", "-sS SYN -sT TCP -sU UDP -O系统", "nmap是网络发现和安全审计工具"),
    ("ethtool", "网卡配置", "-i驱动 -k特性 -S统计", "ethtool查询和配置网卡参数"),
    ("ip", "网络配置", "addr地址 link链路 route路由 netns命名空间", "ip是新一代网络配置工具"),
    ("bridge", "网桥管理", "add/del/show fdb转发", "bridge管理Linux网桥"),
    ("tc", "流量控制", "qdisc队列 class类别 filter过滤", "tc配置Linux流量控制"),
    ("auditctl", "审计规则", "-a添加 -d删除 -l列出", "auditctl管理Linux审计规则"),
    ("ausearch", "审计搜索", "-m类型 -ts时间 -sv成功/失败", "ausearch搜索审计日志"),
    ("semanage", "SELinux管理", "login/user/port/fcontext", "semanage管理SELinux策略"),
    ("restorecon", "恢复上下文", "-R递归 -v详细 -F强制", "restorecon恢复文件SELinux上下文"),
    ("getenforce/setenforce", "SELinux模式", "Enforcing/Permissive/Disabled", "getenforce查看setenforce设置SELinux模式"),
    ("chage", "密码策略", "-l列出 -M最大天数 -m最小天数 -W警告", "chage管理用户密码过期策略"),
    ("passwd", "修改密码", "-l锁定 -u解锁 -e过期 -d删除", "passwd修改用户密码"),
    ("useradd/userdel", "用户管理", "-m创建家目录 -s shell -g组 -G附加组", "useradd创建userdel删除用户"),
    ("groupadd/groupdel", "组管理", "-g GID -r系统组", "groupadd创建groupdel删除组"),
    ("su/sudo", "切换用户", "su切换 sudo提权 visudo编辑", "su切换用户sudo以其他用户执行命令"),
    ("w/who", "登录用户", "w详细 who简单", "w和who显示当前登录用户"),
    ("last", "登录记录", "-n数量 -f文件", "last显示用户登录历史记录"),
    ("nproc", "CPU核心数", "无参数", "nproc显示可用CPU核心数"),
    ("uname", "系统信息", "-a全部 -r内核 -m架构", "uname显示系统信息"),
    ("hostname", "主机名", "-f FQDN -I IP -d域名", "hostname显示或设置主机名"),
    ("uptime", "运行时间", "无参数", "uptime显示系统运行时间和负载"),
    ("date", "日期时间", "+%Y%m%d格式 -s设置 -d解析", "date显示或设置系统日期时间"),
    ("cal", "日历", "-3三个月 -y全年 -m周一起", "cal显示日历"),
    ("time", "计时", "real实际 user用户 sys系统", "time测量命令执行时间"),
    ("timeout", "超时执行", "-s信号 -k杀死 -v详细", "timeout在指定时间后终止命令"),
    ("watch", "定期执行", "-n间隔 -d差异 -g退出", "watch定期执行命令并显示输出"),
    ("at", "一次性定时", "at HH:MM atq查询 atrm删除", "at执行一次性定时任务"),
    ("batch", "负载定时", "系统负载低时执行", "batch在系统负载低时执行任务"),
    ("logrotate", "日志轮转", "-f强制 -d调试 -v详细", "logrotate自动轮转压缩和删除日志"),
    ("iconv", "编码转换", "-f源编码 -t目标编码 -o输出", "iconv转换文件编码"),
    ("base64", "编解码", "-d解码 -w换行", "base64编码或解码数据"),
    ("md5sum/sha256sum", "校验和", "-c校验 --status静默", "md5sum/sha256sum计算和校验文件哈希"),
    ("xargs", "参数构建", "-n每行数 -I替换 -P并行", "xargs将输入转为命令参数"),
    ("seq", "序列", "首 增量 末 -s分隔符 -w等宽", "seq生成数字序列"),
    ("shuf", "随机", "-n数量 -e列表 -i范围", "shuf生成随机排列"),
    ("tee", "分流", "-a追加 -i忽略中断", "tee输出到文件和标准输出"),
    ("trap", "信号处理", "trap 'cmd' SIGNAL", "trap在Shell脚本中捕获信号"),
    ("getopts", "选项解析", "optstring name", "getopts解析Shell脚本选项参数"),
    ("printf", "格式化输出", "%s字符串 %d整数 %f浮点", "printf格式化输出，比echo更灵活"),
    ("expr", "表达式求值", "算术运算、字符串操作、比较", "expr计算表达式值"),
    ("bc", "计算器", "-l数学库 -q静默 scale=精度", "bc是任意精度计算器"),
    ("awk", "文本处理", "BEGIN/END 模式{动作}", "awk是强大的文本处理语言"),
    ("sed", "流编辑", "s替换 d删除 a追加 i插入", "sed是流编辑器，逐行处理文本"),
    ("jq", "JSON处理", ".key [] | select() map()", "jq是命令行JSON处理器"),
    ("yq", "YAML处理", ".key [] | select()", "yq是命令行YAML/JSON/XML处理器"),
    ("helm", "K8s包管理", "install/upgrade/rollback/template", "helm是Kubernetes包管理器"),
    ("argocd", "GitOps", "app sync diff list", "argocd是Kubernetes GitOps持续交付工具"),
    ("terraform", "基础设施即代码", "plan/apply/destroy/import", "terraform管理云基础设施资源"),
    ("ansible", "配置管理", "playbook ad-hoc inventory", "ansible是自动化配置管理工具"),
    ("consul", "服务发现", "members kv catalog", "consul提供服务发现和配置管理"),
    ("vault", "密钥管理", "seal/unseal kv auth", "vault管理密钥和敏感数据"),
    ("prometheus", "监控", "query targets alerts", "prometheus是时序数据库和监控系统"),
    ("grafana", "可视化", "dashboard panel data source", "grafana是监控数据可视化平台"),
    ("jaeger", "链路追踪", "trace search dependencies", "jaeger是分布式链路追踪系统"),
    ("fluentd", "日志收集", "input/filter/output", "fluentd是统一日志收集层"),
    ("istioctl", "服务网格", "analyze dashboard install", "istioctl管理Istio服务网格"),
    ("k9s", "K8s终端UI", "交互式K8s资源浏览", "k9s是Kubernetes终端UI管理工具"),
    ("stern", "多Pod日志", "pod1 pod2 -c容器", "stern同时查看多个Pod日志"),
    ("kubectx/kubens", "K8s上下文", "切换集群/命名空间", "kubectx/kubens快速切换K8s上下文和命名空间"),
    ("skaffold", "K8s开发", "dev/run/debug", "skaffold是K8s应用开发工作流工具"),
    ("tilt", "K8s开发", "自动构建部署热重载", "tilt是K8s多服务开发环境工具"),
]

for i, (cmd, desc, params, detail) in enumerate(os_data):
    os_extra.append({
        'id': f'os-cmd-{i+1}',
        'title': f'Linux中{cmd}命令的作用和使用方法？',
        'category': 'os',
        'difficulty': 'easy',
        'content': f'{cmd}命令用于{desc}。常用参数：{params}。',
        'answer': f'{cmd}是Linux常用命令，用于{desc}。常用参数：{params}。{detail}。掌握{cmd}是Linux运维和开发的基本技能。',
        'sourceType': 'builtin',
        'source': 'Linux命令速查',
        'tags': ['Linux', '命令'],
    })

# Language extra questions
lang_extra = []
lang_data = [
    ("Java的HashMap和ConcurrentHashMap的区别？", "hard", "HashMap线程不安全，ConcurrentHashMap线程安全。JDK1.8的ConcurrentHashMap使用CAS+synchronized锁桶节点，锁粒度更细。不允许key/value为null。"),
    ("Java的线程生命周期？", "medium", "六种状态：NEW(新建)、RUNNABLE(可运行)、BLOCKED(阻塞)、WAITING(等待)、TIMED_WAITING(超时等待)、TERMINATED(终止)。wait()进入WAITING，sleep()进入TIMED_WAITING。"),
    ("Java的类加载机制？双亲委派？", "hard", "类加载五步：加载->验证->准备->解析->初始化。双亲委派：先让父类加载器加载，父类无法加载时自己加载。保证核心类不被篡改。可以打破：SPI、Tomcat。"),
    ("Java的泛型擦除？", "medium", "Java泛型在编译时擦除为原始类型。List<String>运行时是List。通过反射可以绕过泛型检查。PECS原则：Producer Extends Consumer Super。"),
    ("Java的Stream API？", "medium", "Stream是函数式数据处理API。中间操作：filter/map/flatMap/sorted/distinct。终端操作：forEach/collect/reduce/count。并行流parallelStream()利用多核。"),
    ("Java的Optional类？", "easy", "Optional是空值安全的容器。创建：of()/ofNullable()/empty()。操作：isPresent()/ifPresent()/orElse()/orElseGet()/orElseThrow()/map()/flatMap()。避免null检查。"),
    ("Java的CompletableFuture？", "hard", "CompletableFuture是异步编程工具。创建：supplyAsync()/runAsync()。组合：thenApply/thenCompose/allOf/anyOf。异常：exceptionally/handle。比Future更灵活。"),
    ("Java的Record类？", "easy", "Record是Java 14+的不可变数据类。自动生成：构造器、getter、equals、hashCode、toString。不可继承、字段final。适合DTO和值对象。"),
    ("Java的密封类(Sealed Class)？", "medium", "密封类(Java 17+)限制哪些类可以继承它。permits子句指定允许的子类。与switch模式匹配配合实现穷举检查。"),
    ("Java的虚拟线程(Virtual Thread)？", "hard", "虚拟线程(Java 21+)是轻量级线程，由JVM调度而非OS。创建：Thread.ofVirtual()。百万级虚拟线程可行。适合IO密集型任务。与平台线程1:1映射不同。"),
    ("C++的RAII？", "medium", "RAII(资源获取即初始化)：构造时获取资源，析构时释放资源。智能指针、lock_guard、fstream都是RAII。保证异常安全，防止资源泄漏。"),
    ("C++的移动语义和完美转发？", "hard", "移动语义：右值引用(&&)和move()转移资源。完美转发：forward<T>()保持值类别。引用折叠：T& && = T&。用于泛型编程和容器实现。"),
    ("C++的模板元编程？", "hard", "模板元编程在编译时计算。递归模板实例化实现循环，特化实现条件。type_traits提供编译时类型检查。C++17的if constexpr简化编译时分支。"),
    ("C++的内存模型？", "hard", "C++11定义6种内存序：memory_order_relaxed/acquire/release/acq_rel/seq_cst/consume。seq_cst最严格，relaxed最宽松。用于实现无锁数据结构。"),
    ("Python的上下文管理器？", "medium", "with语句使用上下文管理器。实现__enter__和__exit__方法。contextlib.contextmanager装饰器简化创建。用于资源管理(文件、锁、连接)。"),
    ("Python的asyncio？", "hard", "asyncio是Python异步IO框架。核心：事件循环、协程(async/await)、Future、Task。asyncio.gather()并行执行。aiohttp异步HTTP。适合IO密集型。"),
    ("Python的元类(metaclass)？", "hard", "元类是类的类，控制类的创建。type是默认元类。自定义元类继承type，重写__new__或__init__。ORM框架(Django/SQLAlchemy)使用元类。"),
    ("Python的描述符(descriptor)？", "hard", "描述符是实现__get__/__set__/__delete__的对象。数据描述符(有__set__)优先级高于实例属性。property是描述符。用于属性验证和计算属性。"),
    ("Go的泛型？", "medium", "Go 1.18+支持泛型。类型参数：func Foo[T any](x T)。约束：interface{...}。内置约束：comparable/any。类型推断简化调用。"),
    ("Go的错误处理？", "easy", "Go使用多返回值返回error。if err != nil检查。errors.Is/As判断错误类型。panic/recover处理不可恢复错误。defer确保资源释放。"),
    ("Go的context包？", "medium", "context用于传递截止时间、取消信号和值。WithCancel/WithTimeout/WithValue。函数第一个参数通常是ctx。用于请求超时和级联取消。"),
    ("Go的反射(reflect)？", "medium", "reflect包运行时检查类型。TypeOf()获取类型，ValueOf()获取值。NumField()/Field()遍历结构体。用于JSON序列化、ORM映射。性能较差。"),
    ("Rust的trait？", "medium", "trait类似接口，定义行为。impl Trait for Type实现。trait bound约束泛型。关联类型。默认实现。derive宏自动实现常见trait(Debug/Clone)。"),
    ("Rust的并发模型？", "hard", "Rust通过所有权保证线程安全。Send trait表示可跨线程传递，Sync表示可跨线程共享。Arc(原子引用计数)+Mutex/RwLock实现共享状态。通道mpsc通信。"),
    ("Rust的宏系统？", "hard", "两种宏：1.声明宏(macro_rules!)模式匹配 2.过程宏(proc_macro)自定义derive/属性/函数式。宏在编译时展开，零运行时开销。"),
    ("Rust的Pin和Unpin？", "hard", "Pin防止值在内存中移动。自引用结构需要Pin。Unpin表示可以安全移动(大多数类型)。async/await生成的Future需要Pin。"),
    ("Rust的Unsafe？", "medium", "unsafe允许：1.解引用裸指针 2.调用unsafe函数 3.访问可变静态变量 4.实现unsafe trait 5.访问union字段。用于FFI和底层操作。"),
    ("Rust的Cargo？", "easy", "Cargo是Rust的包管理器和构建工具。cargo build/run/test/doc/publish。Cargo.toml配置依赖。workspace管理多包。features条件编译。"),
    ("Rust的错误处理？", "medium", "Result<T,E>可恢复错误，panic!不可恢复。?运算符传播错误。thiserror/anyhow库简化错误处理。自定义错误类型实现std::error::Error。"),
    ("Rust的异步编程？", "hard", "async/await语法。Future trait。tokio异步运行时。async fn返回impl Future。Pin保证自引用安全。spawn创建异步任务。select!并发等待。"),
    ("什么是JIT编译？", "medium", "JIT(即时编译)在运行时将字节码编译为机器码。热点代码编译优化。Java的JVM、JavaScript的V8使用JIT。比解释快，比AOT灵活。"),
    ("什么是GC调优？", "hard", "JVM GC调优参数：-Xms/-Xmx堆大小、-XX:+UseG1GC选择收集器、-XX:MaxGCPauseMillis目标暂停时间。工具：jstat、jmap、GCViewer。"),
    ("什么是内存模型？", "hard", "内存模型定义多线程访问内存的规则。Java Memory Model：happens-before关系保证可见性。volatile、synchronized、final建立happens-before。"),
    ("什么是协程？", "medium", "协程是用户态轻量级线程。由程序控制切换，不需要内核参与。Python asyncio、Go goroutine、Kotlin协程。比线程开销小，适合IO密集型。"),
    ("什么是Actor模型？", "medium", "Actor模型中每个Actor有独立状态和邮箱，通过消息通信。不共享内存。Erlang/Akka使用Actor模型。优点：无锁并发、容错、分布式。"),
    ("什么是CSP模型？", "medium", "CSP(通信顺序进程)通过通道通信，不共享内存。Go语言基于CSP模型。goroutine+channel。与Actor区别：通道是第一类对象，不绑定特定进程。"),
    ("什么是尾递归优化？", "medium", "尾递归：递归调用是函数最后操作。编译器将其优化为循环，避免栈溢出。函数式语言(Haskell/Scala)支持。Python/Java不支持尾递归优化。"),
    ("什么是模式匹配？", "medium", "模式匹配检查数据结构是否符合模式。Rust的match、Scala的case、Haskell的模式。比switch更强大：解构、守卫、嵌套。编译器检查穷举性。"),
    ("什么是代数数据类型(ADT)？", "medium", "ADT是类型组合方式：和类型(Sum，或)和积类型(Product，与)。Rust的enum是Sum类型，struct是Product类型。用于建模领域。"),
    ("什么是类型推导？", "medium", "类型推导自动推断表达式类型。Haskell全推导，C++ auto，Java var，Go :=。减少冗余类型标注，但需要可读性权衡。"),
    ("什么是高阶函数？", "easy", "高阶函数接收或返回函数。map/filter/reduce/sort都是高阶函数。闭包/lambda是匿名函数。函数组合：f.g = f(g(x))。"),
    ("什么是单子(Monad)？", "hard", "Monad是函数式编程的抽象。操作：return(包装)和bind(>>=，链式操作)。Maybe/IO/List都是Monad。用于处理副作用和计算链。"),
    ("什么是不可变数据结构？", "medium", "不可变数据创建后不能修改。修改操作返回新副本(结构共享)。优点：线程安全、可缓存、易推理。Clojure/Haskell默认不可变。持久化数据结构。"),
    ("什么是尾调用优化(TCO)？", "medium", "TCO将尾位置的函数调用优化为跳转，不增加栈帧。ES6严格模式支持但浏览器实现不一致。函数式语言普遍支持。避免递归栈溢出。"),
    ("什么是惰性求值？", "medium", "惰性求值只在需要时计算。Haskell默认惰性。Python生成器、Java Stream.lazy。优点：无限数据结构、避免不必要计算。缺点：内存泄漏、难以预测性能。"),
    ("什么是动态分发和静态分发？", "medium", "静态分发：编译时确定调用(泛型/内联)，零开销。动态分发：运行时确定(vtable/接口)，有间接调用开销。Rust的impl Trait vs dyn Trait。"),
    ("什么是零成本抽象？", "medium", "零成本抽象：高级抽象不引入运行时开销。Rust的迭代器、C++的模板、Go的接口。编译时优化掉抽象层。'你不需要为你不用的功能付费'。"),
    ("什么是内存对齐？", "medium", "内存对齐要求数据存储在特定边界上。CPU访问对齐内存更快。struct字段顺序影响大小。Rust/C++可用repr(C/align)控制。"),
    ("什么是ABI稳定性？", "medium", "ABI(应用二进制接口)定义编译后的接口。C ABI最稳定。C++ ABI不稳定(name mangling)。Rust暂无稳定ABI。跨语言调用用C ABI。"),
    ("什么是增量编译？", "medium", "增量编译只重新编译变化的部分。Rust/Cargo支持增量编译。Go编译本身很快。Java增量编译(Gradle)。减少开发时的等待时间。"),
    ("什么是交叉编译？", "medium", "交叉编译在一个平台生成另一个平台的可执行文件。Go：GOOS/GOARCH。Rust：target。C/C++：toolchain。用于嵌入式和移动开发。"),
    ("什么是LSP(Language Server Protocol)？", "easy", "LSP是微软定义的编辑器-语言服务通信协议。统一了代码补全、跳转、诊断等功能。各大语言都有LSP实现。VS Code基于LSP。"),
    ("什么是DAP(Debug Adapter Protocol)？", "medium", "DAP是调试适配器协议，统一编辑器和调试器通信。类似LSP的调试版。VS Code基于DAP。各语言实现Debug Adapter。"),
    ("什么是构建图(Build Graph)？", "medium", "构建图描述编译依赖关系。DAG(有向无环图)。增量编译基于构建图。Bazel/Buck构建大规模项目。任务并行执行。"),
    ("什么是语义化版本(SemVer)？", "easy", "SemVer格式：MAJOR.MINOR.PATCH。MAJOR不兼容变更，MINOR向后兼容新功能，PATCH向后兼容修复。预发布：1.0.0-alpha。依赖管理基础。"),
    ("什么是依赖注入(DI)？", "medium", "DI将依赖从外部注入而非内部创建。方式：1.构造器注入 2.Setter注入 3.接口注入。Spring IoC容器自动注入。降低耦合，提高可测试性。"),
    ("什么是SOLID原则？", "medium", "SOLID：1.单一职责(SRP) 2.开闭(OCP) 3.里氏替换(LSP) 4.接口隔离(ISP) 5.依赖反转(DIP)。面向对象设计的基本原则。"),
    ("什么是设计模式中的创建型模式？", "medium", "创建型：1.单例(唯一实例) 2.工厂方法(子类决定创建) 3.抽象工厂(产品族) 4.建造者(分步构建) 5.原型(克隆)。关注对象创建机制。"),
    ("什么是设计模式中的结构型模式？", "medium", "结构型：1.适配器(接口转换) 2.桥接(抽象与实现分离) 3.组合(树形结构) 4.装饰器(动态添加功能) 5.外观(简化接口) 6.享元(共享对象) 7.代理(访问控制)。"),
    ("什么是设计模式中的行为型模式？", "medium", "行为型：1.责任链(请求链式处理) 2.命令(请求对象化) 3.迭代器(顺序访问) 4.中介者(对象间通信) 5.备忘录(状态保存) 6.观察者(通知依赖) 7.状态(状态切换) 8.策略(算法族) 9.模板方法(算法骨架) 10.访问者(操作与结构分离)。"),
    ("什么是DDD(领域驱动设计)？", "hard", "DDD核心概念：1.限界上下文(Bounded Context) 2.聚合(Aggregate) 3.领域事件 4.值对象 5.实体 6.仓储(Repository)。战略设计和战术设计。"),
    ("什么是CQRS？", "hard", "CQRS(命令查询职责分离)：写操作(命令)和读操作(查询)使用不同模型。写模型保证一致性，读模型优化查询。常与Event Sourcing配合。"),
    ("什么是Event Sourcing？", "hard", "Event Sourcing不存储当前状态，而是存储所有事件。状态通过回放事件重建。优点：完整审计、时间旅行、事件驱动。缺点：事件量大、最终一致性。"),
]

for i, (title, diff, answer) in enumerate(lang_data):
    lang_extra.append({
        'id': f'lang-extra-{i+1}',
        'title': title,
        'category': 'language',
        'difficulty': diff,
        'content': answer[:200],
        'answer': answer,
        'sourceType': 'builtin',
        'source': '面试高频题',
        'tags': ['编程语言'],
    })

print(f"OS extra: {len(os_extra)}")
print(f"Language extra: {len(lang_extra)}")

# Inject into index.html
with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

pattern = r'const BUILTIN_QUESTIONS=\[([\s\S]*?)\];'
match = re.search(pattern, html)
if not match:
    print("Could not find BUILTIN_QUESTIONS!")
    exit(1)

all_extra = os_extra + lang_extra
js_items = []
for q in all_extra:
    tags_str = json.dumps(q.get('tags', []), ensure_ascii=False)
    item = f"{{id:'{q['id']}',title:{json.dumps(q['title'], ensure_ascii=False)},category:'{q['category']}',difficulty:'{q['difficulty']}',content:{json.dumps(q['content'], ensure_ascii=False)},answer:{json.dumps(q.get('answer',''), ensure_ascii=False)},sourceType:'builtin',source:{json.dumps(q['source'], ensure_ascii=False)},tags:{tags_str}}}"
    js_items.append(item)

js_code = ','.join(js_items)
insert_pos = match.end() - 2
new_html = html[:insert_pos] + ',' + js_code + html[insert_pos:]

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(new_html)

print(f"Added {len(all_extra)} extra questions")
