import json
import re

all_new_questions = []

# ============== NETWORK: ~130 questions ==============
net_qs = [
    ("TCP/IP模型有几层？每层的作用？", "easy", "TCP/IP四层：应用层(HTTP/FTP/DNS)、传输层(TCP/UDP)、网络层(IP/ICMP/ARP)、网络接口层(以太网/WiFi)。OSI七层多了表示层和会话层。每一层封装本层头部为上层提供服务。"),
    ("TCP和UDP的区别？适用场景？", "easy", "TCP：面向连接、可靠(ACK重传)、流量控制(滑动窗口)、拥塞控制、字节流。适用HTTP/HTTPS/FTP/SMTP/SSH。UDP：无连接、不可靠、数据报、速度快。适用DNS/DHCP/视频通话/游戏/QUIC。QUIC基于UDP实现可靠传输。"),
    ("TCP三次握手详细过程？SYN攻击？", "medium", "1.客户端发SYN(seq=x) 2.服务器回SYN+ACK(seq=y ack=x+1) 3.客户端发ACK(ack=y+1)。SYN Flood：大量伪造SYN不完成握手耗尽半连接队列(SYN_RECV)。防御：SYN Cookie、增大backlog、防火墙过滤。"),
    ("TCP四次挥手？TIME_WAIT作用？", "medium", "主动方FIN->被动方ACK->被动方FIN->主动方ACK。TIME_WAIT(2MSL)：1.确保最后ACK到达 2.等待迟到的报文消散。过多TIME_WAIT：启用reuseaddr/recycle端口复用、调整tcp_tw_reuse。"),
    ("TCP滑动窗口？流量控制？", "medium", "窗口：接收方告知发送方可接收的数据量(rwnd)。发送方根据窗口大小控制发送速率。零窗口探测：接收方窗口0时定期发送探测。Nagle算法合并小包减少网络小分组。糊涂窗口综合征需避免。"),
    ("TCP拥塞控制？慢启动/拥塞避免/快重传/快恢复？", "hard", "慢启动：cwnd指数增长至ssthresh。拥塞避免：cwnd线性增长。快重传：3个重复ACK立即重传不等超时。快恢复：cwnd减半+3而非降为1。BBR/CUBIC是现代算法。ECN显式拥塞通知。"),
    ("TCP粘包/拆包？如何解决？", "medium", "TCP字节流无消息边界。粘包多条消息合并，拆包一条消息分多包。解决：1.定长消息 2.分隔符(\\n/r\\n) 3.长度字段(Length Field) 4.应用层协议设计。Netty的DelimiterBasedFrameDecoder/LengthFieldBasedFrameDecoder解决。"),
    ("什么是MTU和MSS？关系？", "easy", "MTU(Maximum Transmission Unit)：数据链路层最大传输单元，以太网1500字节。MSS(Maximum Segment Size)：TCP层数据最大大小=MTU-40(IP+TCP头)=1460。Path MTU Discovery发现路径最小MTU。DF(Don't Fragment)标志。IP分片影响性能应避免。"),
    ("ARP协议工作原理？ARP欺骗攻击？", "medium", "ARP(Address Resolution Protocol)：IP->MAC映射。请求广播响应单播。ARP缓存表有老化时间。ARP欺骗：伪造ARP响应欺骗网关或受害者实现MITM中间人攻击。防御：静态ARP绑定、DAI(Dynamic ARP Inspection)、802.1x认证。"),
    ("ICMP协议？ping和traceroute原理？", "medium", "ICMP(Internet Control Message Protocol)：网络层差错报告和控制。Echo Request/Reply(ping连通性测试)。Time Exceeded(traceroute TTL递增路由追踪)。Destination Unreachable(目标不可达)。ICMP Rate Limiting防洪水。防火墙常禁ping但ICMP Path MTU Discovery需放行。"),
    ("DNS解析过程？递归查询vs迭代查询？", "medium", "域名->IP：浏览器缓存->OS缓存->hosts文件->本地DNS服务器(递归)->根域(.)->顶级域(.com/.cn)->权威域NS。递归：DNS服务器代查全部。迭代：客户端逐步查询。DNS预取、HTTP/2连接合并减少DNS查询次数提升速度。"),
    ("DNS记录类型？A/AAAA/CNAME/MX/TXT/NS/SOA/PTR？", "easy", "A：IPv4地址。AAAA：IPv6地址。CNAME：别名域名。MX：邮件交换服务器。TXT：文本记录(SPF DKIM验证)。NS：名称服务器。SOA：授权起始(主服务器信息)。PTR：反向解析(IP->域名)。SRV：服务定位。CAA：证书颁发机构授权。"),
    ("DNS劫持和DNS污染？区别与防护？", "medium", "DNS劫持：篡改DNS服务器返回结果(运营商劫持广告)。DNS污染：在查询路径上注入假响应(防火墙GFW)。防护：DoH(DNS over HTTPS加密查询443端口)、DoT(DNS over TLS 853端口)、可信DNS(8.8.8.8/1.1.1.1)、本地hosts文件。"),
    ("HTTP/1.0 vs HTTP/1.1 vs HTTP/2 vs HTTP/3对比？", "medium", "HTTP/1.0：短连接。HTTP/1.1：长连接Keep-Alive、管线化(难部署)、Host头。HTTP/2：二进制帧、多路复用(无队头阻塞)、HPACK头部压缩、服务端推送。HTTP/3：基于QUIC(UDP)、0-RTT快速握手、连接迁移(网络切换不断连)。性能逐代大幅提升。"),
    ("HTTP状态码分类？常见状态码含义？", "easy", "1xx信息(100 Continue继续发送体)。2xx成功(200 OK / 201 Created / 204 No Content)。3xx重定向(301永久 / 302临时 / 304未修改)。4xx客户端错误(400参数错 / 401未认证 / 403禁止 / 404不存在)。5xx服务端错误(500内部错 / 502网关错 / 503不可用 / 504超时)。"),
    ("HTTP请求方法？GET POST PUT DELETE PATCH RESTful？", "easy", "GET获取资源(幂等可缓存)。POST创建资源(非幂等)。PUT整体更新(幂等)。PATCH部分更新(非幂等)。DELETE删除(幂等)。HEAD获取头元数据。OPTIONS预检(CORS)。CONNECT建立隧道。TRACE调试回环。RESTful：名词URI+动词HTTP方法+状态码+JSON。"),
    ("Cookie和Session？Token(JWT)？区别与选择？", "medium", "Cookie：客户端存储，每次请求自动携带，4KB限制，可设HttpOnly/Secure/SameSite安全属性。Session：服务端存储，Cookie存Session ID，服务端可控销毁。JWT(Json Web Token)：自包含签名令牌三段header.payload.signature，无状态但payload Base64不加密勿存敏感信息。现代Web API倾向JWT Stateless。"),
    ("HTTPS？TLS/SSL握手过程？版本？", "medium", "TLS握手：1.ClientHello(版本密码套件随机数) 2.ServerHello(选择套件证书随机数) 3.客户端验证证书链 4.密钥交换(ECDHE前向保密或RSA) 5.双方生成会话密钥 6.Finished加密通信开始。TLS 1.3(2018)：仅需1-RTT握手，强制前向保密，移除不安全算法。0-RTT恢复先前连接更快但有重放风险需防范。Session Ticket/PSK复用。"),
    ("对称加密和非对称加密？RSA/ECC/AES/ChaCha20？", "medium", "对称加密：加解密相同密钥。AES-256-GCM( Intel AES-NI硬件加速推荐)、ChaCha20-Poly1305( ARM移动端无AES指令集时更快)。非对称：公钥加密私钥解密/私钥签名公钥验签。RSA-2048+/ECDSA(secp256r1/secp384r1椭圆曲线)。混合加密：非对称交换对称密钥+对称加密数据体。TLS使用此模式。ECC同安全级别密钥远短于RSA。"),
    ("XSS攻击类型和防御措施？", "medium", "XSS(Cross Site Scripting)：注入恶意JS脚本执行。存储型：存入数据库所有用户受害。反射型：URL参数反射触发。DOM型：前端JS修改DOM触发。防御：输出编码转义(HTML实体编码)、CSP(Content-Security-Policy白名单资源来源)、HttpOnly Cookie防窃取、Input Sanitization输入净化(白名单优先)。"),
    ("CSRF攻击原理和防御？", "medium", "CSRF(Cross Site Request Forgery)：诱导用户在已登录状态发起恶意请求(利用浏览器自动携带Cookie)。SameSite Cookie属性(Strict严格/Lax宽松/None跨站需Secure)。CSRF Token表单隐藏字段+服务端校验。Referer/Origin头检查来源合法性。GET请求不应修改状态(幂等)。双重Cookie验证方案。"),
    ("SQL注入攻击和防御？", "medium", "SQL Injection：拼接用户输入破坏SQL语句结构导致数据泄露或篡改。经典' OR '1'='1万能密码。防御核心：参数化查询(PreparedStatement/Statement占位符)最有效！ORM框架(Hibernate/MyBatis #{})自动参数化。输入验证白名单。最小权限数据库账号。WAF辅助检测拦截异常模式。MyBatis ${}字符串拼接危险勿用！"),
    ("DDoS攻击类型和防御策略？", "hard", "DDoS分布式拒绝服务：海量傀儡机同时请求耗尽目标资源。Volumetric(流量型)：UDP/ICMP Flood填满带宽管道。Protocol(协议型)：SYN Flood耗尽半连接队列。Application(应用层)：HTTP Flood模拟正常请求耗尽应用资源。防御：CDN分散流量到全球节点、Anycast分散入口、Rate Limiting限流、Challenge-Response(CAPTCHA人机验证)、黑洞路由Null Route丢弃、专业清洗中心 Scrubbing Center流量清洗后回源。云厂商DDoS防护(阿里云DDoS/AWS Shield)。高防IP。"),
    ("负载均衡四层L4和七层L7？算法？", "medium", "四层(L4)：传输层基于IP+port转发，LVS/F5/Nginx stream模块。七层(L7)：应用层基于HTTP内容路由，Nginx/HAProxy/Traefik。算法：RR轮询(Round Robin)、加权WRR(Weighted RR按配置比例)、最少连接LC(Least Connections分配给空闲者)、IP Hash(同一IP始终同一后端保持会话)、一致性哈希Consistent Hash(缓存节点分布均匀增删影响最小)。健康检查Health Check剔除故障节点。云SLB/ALB/NLB。"),
    ("反向代理vs正向代理？Nginx配置？", "easy", "正向代理：客户端代理帮助客户端访问外部隐藏客户端IP(翻墙/抓包)。反向代理：服务端代理对外代表服务器隐藏内部架构提供负载均衡/缓存/SSL卸载/WAF/压缩功能。Nginx：upstream定义后端server池(weight权重backup备选max_fails失败次数fail_timeout)。proxy_pass转发请求。location匹配规则(=精确 ^~前缀 ~正则)。gzip on压缩。ssl_certificate配置HTTPS。"),
    ("WebSocket协议？握手帧格式？心跳？", "medium", "WS全双工通信持久连接。握手：HTTP Upgrade: websocket请求 + 101 Switching Protocols响应完成协议升级。帧格式：FIN结束标志 OPCODE操作码(0x1文本0x2二进制0x8关闭0x9心跳ping 0xA心跳pong) MASK掩码位 PAYLOAD LENGTH载荷长度(126/127扩展) PAYLOAD载荷数据。wss://加密版本。心跳ping/pong保活检测连接存活性防止半开连接。Socket.IO封装自动重连/房间Room/ACK确认机制简化开发。"),
    ("OAuth 2.0流程？授权码模式最安全？", "medium", "OAuth 2.0第三方授权框架四种模式：授权码Authorization Code(最安全！服务端交互token不经过浏览器可PKCE增强)、隐式Implicit(token直接返浏览器安全性差已不推荐)、客户端凭证Client Credentials(机器对机器M2M)、设备码Device Code(电视/打印机等无浏览器设备)。OIDC(OpenID Connect)在OAuth2.0基础上添加id_token(JWT包含用户身份信息)实现单点登录SSO。Scope权限范围控制。Refresh Token刷新Access Token延长会话无需重新授权。"),
    ("RPC框架gRPC？Protobuf？HTTP/2优势？", "medium", "gRPC Google开源高性能RPC框架：HTTP/2 + Protobuf序列化 + IDL接口定义语言(.proto文件)。四种调用模式：Unary一元(一次请求一次响应)、Server Streaming服务端流式、Client Streaming客户端流式、Bidirectional双向流式。Protobuf二进制序列化比JSON/XML体积小3-10倍速度快20-100倍(Varint编码/ZigZag/字段编号省空间)。HTTP/2多路复用/头部压缩/服务端推送/二进制帧提升性能。代码生成多语言支持(Java/Go/Python/C++/Node.js/Rust...)。Streaming gRPC适合实时数据推送。"),
    ("消息队列MQ？Kafka/RabbitMQ/RocketMQ选型？", "medium", "MQ核心价值：异步解耦(削峰填谷)、可靠传输(持久化+确认机制)。Kafka：超高吞吐(百万级TPS)、分区副本分布式、消费者组、日志追加写磁盘顺序IO高效、Exactly-Once语义。适合日志收集/用户行为/流处理。RabbitMQ：AMQP协议灵活路由Exchange+Binding、可靠性高(发布确认+持久化+手动ACK)、管理UI友好。适合传统业务异步任务。RocketMQ阿里开源：事务消息(半消息机制)、定时消息(延迟等级)、Tag消息过滤、万亿级消息堆积能力。选型依据：吞吐量/可靠性/功能需求/团队熟悉度/生态。"),
    ("微服务通信方式同步vs异步？Service Mesh？", "medium", "同步通信：HTTP/REST/gRPC实时响应但耦合等待超时复杂。异步通信：消息队列(Kafka/RabbitMQ)/事件总线(EventBus)解耦最终一致但调试追踪难延迟不确定。Service Mesh服务网格(Istio/Linkerd)：Sidecar代理模式处理通信基础设施(熔断Circuit Breaker/重试Retry/超时Timeout/追踪Tracing/认证mTLS/观测性Metrics)，业务代码零侵入。Control Plane控制平面(istiod Pilot Citadel Galley) + Data Plane数据平面(Envoy Sidecar)。VirtualService路由规则 DestinationRule子集/负载均衡/熔断。降低微服务复杂度但增加运维复杂度和资源开销(Sidecar每个Pod额外消耗)。"),
    ("熔断器Circuit Breaker？降级Degradation？限流Rate Limiting？", "medium", "熔断Hystrix/Sentinel/Resilience4j：故障率达到阈值打开熔断器(Circuit Open)快速失败Fail Fast而非无限等待保护级联故障。Half-Open半开状态试探性放行少量请求判断是否恢复(Close闭合)。降级：非核心功能暂停保核心可用(返回默认值/静态页面/友好提示)。限流：令牌桶Token Bucket(恒定速率+突发容忍)/漏桶Leaky Bucket(匀速输出)/滑动窗口Sliding Window Log/Counter(精度更高)。Sentinel阿里开源：规则配置 Dashboard可视化、自适应限流Adaptive(自动根据系统负载调整)、热点参数限流、集群限流、授权黑白名单。维度：用户/IP/API Key/全局接口级。429 Too Many Requests + Retry-After响应头告知客户端。"),
    ("API网关API Gateway？Kong/APISIX/Zuul？", "medium", "API Gateway统一入口职责：路由转发Routing(基于Path/Header/Query/Cookie到后端服务)、认证鉴权AuthN/AuthZ(OAuth2.0/JWT Token/API Key/HMAC签名)、协议转换Protocol Translation(gRPC<->REST JSON/GraphQL)、限流熔断Rate Limit & Circuit Breaker、日志监控Logging Metrics Tracing(统一RequestId串联全链路)、缓存Cache、请求响应转换Transformation、API版本管理Versioning。Kong(基于OpenResty Nginx+Lua插件生态丰富300+插件社区活跃)。APISIX(Apache基金会高性能动态路由etcd配置中心热更新)。Spring Cloud Gateway(Java Filter Chain生态)。Envoy(云原生Istio数据面)。BFF Backend for Frontend面向不同客户端(Web/iOS/Android)裁剪适配层。部署高可用多实例+前置LB。"),
    ("服务发现Service Discovery？Consul/Eureka/Nacos/K8s？", "medium", "服务发现：服务实例启动时注册(Register)自身地址端口元数据到注册中心，下线时注销(Deregister)。消费者从注册中心发现(Discover)可用实例列表(支持健康检查Health Check剔除不健康实例)。Consul(HashiCorp)：Go编写、HTTP DNS双接口、KV存储、多数据中心支持、Watch机制实时推送变更。Eureka(Netflix)：AP模式(Availability Partition客户端缓存容忍网络分区)、自我保护模式(Self Preservation防止误剔)。Nacos(阿里)：注册+配置一体化、支持CP/AP切换、长轮询Push 1s内变更推送、MySQL/内嵌存储。Kubernetes：CoreDNS Service DNS + Endpoint + Label Selector原生服务发现。Client Side(客户端发现) vs Server Side(服务端发现/LB代理)。"),
    ("链路追踪Distributed Tracing？Jaeger/Zipkin/SkyWalking？OTel？", "medium", "分布式链路追踪：Trace(一次完整请求全程唯一ID)、Span(单个操作/调用含起止时间/标签Tags/日志Logs)、Parent-Child父子关系构建调用树(DAG)。OpenTelemetry OTel标准化规范(Trace/Metrics/Logs统一可观测性)。Jaeger(CNCF)：UI友好、采样策略Sampling(概率采样/速率限制/动态)、聚合Aggregation。Zipkin(Uber开源Twitter起源)：简单易部署。SkyWalking(国产吴晟)：Agent字节码注入无侵入、APM一体化(服务拓扑/指标/告警)、支持Java/.NET/Node.js/Go。Trace Context在服务间透传(W3C TraceContext标准b3 propagator)。Span Exporter导出到后端存储(Elasticsearch/Jaeger/Zipkin)。Trace ID关联Metrics和Logs实现联动分析。"),
    ("网络编程IO模型？阻塞/非阻塞/多路复用/信号驱动/异步IO？", "hard", "五种IO模型(Unix Network Programming)：Blocking IO阻塞IO(调用阻塞直到完成如read/write默认)。Nonblocking IO非阻塞IO(立即返回EWOULDBLOCK需轮询polling busy-wait CPU空转)。IO Multiplexing IO多路复用(select/poll/epoll/kqueue)一个线程监听多个fd就绪事件效率最高Linux首选epoll。Signal Driven IO信号驱动IO(SIGIO信号通知数据就绪)。Asynchronous IO异步IO(aio_read aio_write POSIX AIO或io_uring Linux 5.1+)内核完成后通知应用真正的Proactor模式。Reactor反应器模式(多路复用+事件分发回调Handler)和Proactor前摄器模式(异步IO+完成分发)。Netty主从Reactor多线程模型(Boss Group accept + Worker Group IO)。"),
    ("Zero-copy零拷贝技术？应用场景？", "medium", "传统数据拷贝路径：disk -> kernel buffer -> user buffer -> socket buffer -> NIC网卡(4次拷贝2次用户态内核态上下文切换CPU开销大)。mmap映射：disk -> kernel buffer(共享给user) -> socket buffer -> NIC(3次拷贝3次切换)。sendfile系统调用：disk -> kernel buffer -> NIC(2次拷贝2次切换 GPU DMA gather scatter I/O)。splice：两个fd间通过pipe管道传输0次拷贝到用户态(内核内核间DMA)。应用场景：Kafka(零拷贝发送消息到网卡)、Nginx静态文件sendfile on、File Channel.transferTo(Java)。节省CPU周期和内存带宽显著提升吞吐量。代价：无法对数据进行用户态处理(如加密/压缩)需传统路径。"),
    ("TCP Fast Open？QUIC协议特点？", "medium", "TFO TCP Fast Open(RFC7413)：首次握手的SYN/SYN-ACK携带数据 payload实现0-RTT或1-RTT数据发送(减少一个RTT)。要求客户端和服务端都支持并开启fastopen选项。QUIC Quick UDP Internet Connection(Google IETF RFC9000)：基于UDP传输层协议。核心特性：0-RTT/1-RTT握手恢复连接(复用之前Connection ID避免握手)、连接迁移Connection Migration(网络WiFi切4G不断连因为基于Connection ID而非四元组)、无队头头部阻塞Head-of-Line Blocking(独立Stream流丢包只影响该流不影响其他流 unlike TCP single sequence number)、前向 secrecy Forward Secrecy(ECDHE密钥交换)。HTTP/3基于QUIC取代TCP+TLS 1.3+HTTP/2组合。Chrome/Cloudflare全面支持。"),
    ("SDN软件定义网络？OpenFlow？VXLAN Overlay？", "medium", "SDN Software Defined Networking：控制平面Control Plane(集中式智能决策路由策略)和数据平面Data Plane(分布式傻瓜转发设备)分离。控制器Controller(ONOS/OpenDaylight)南向API Southbound(OpenFlow Netconf P4Runtime)下发流表Flow Rule到转发设备Switch。北向API Northbound REST API供上层应用编程。OpenFlow协议：流表Flow Table(Match匹配域+Action动作+Counters计数器+Timeouts超时)匹配+执行。VXLAN Virtual Extensible LAN：Overlay虚拟扩展LAN隧道技术(UDP 4789端口封装原始Ethernet帧)解决VLAN只有4096个ID不足问题(VNI 24-bit 16M租户ID)。Underlay物理网络承载Overlay虚拟网络。云计算VPC Virtual Private Cloud常用VXLAN/Geneve。OVS Open vSwitch软件交换机支持OpenFlow VXLAN。"),
    ("VPN虚拟专用网？IPSec/OpenVPN/WireGuard？Tailscale？", "medium", "VPN Virtual Private Network：加密隧道保护数据机密性和完整性穿越公共互联网。IPSec(Internet Protocol Security)：网络层协议族 AH(Authentication Header认证头无加密)+ESP(Encapsulating Security Payload加密载荷)+IKE(Internet Key Exchange密钥交换)。强安全但配置复杂性能开销较大(NAT-T穿透NAT)。OpenVPN：应用层SSL/TLS协议易部署社区成熟。WireGuard( Jason Donenfeld 2019)：现代内核模块级VPN协议极简(仅4000行C代码!)高性能(比OpenVPN快数倍) Curve25519 ECDH密钥交换 + ChaCha20-Poly1305 AEAD加密。ZeroTrust VPN零信任VPN：Tailscale(基于WireGuard Coordination Server协调NAT穿透+ ACL访问控制组网类似ZeroTier)。Headscale自建Coordination Server开源替代Tailscale SaaS控制平面。适合远程办公/多云互联/IoT设备安全接入。"),
]

for i, (t, d, a) in enumerate(net_qs):
    all_new_questions.append({'id':f'net-{i+1}','title':t,'category':'network','difficulty':d,'content':a[:150],'answer':a,'sourceType':'builtin','source':'计算机网络面试题','tags':['计算机网络']})

# ============== DATABASE: ~130 questions ==============
db_qs = [
    ("事务Transaction ACID特性详解？", "easy", "事务是一组操作的逻辑单元要么全部成功(COMMIT)要么全部回滚(ROLLBACK)保证数据一致性。A原子性Atomicity：不可分割的最小执行单元全部成功或全部撤销Undo Log回滚。C一致性Consistency：事务前后数据库从一个合法状态转变到另一个合法状态(满足约束/触发器/级联)。I隔离性Isolation：并发事务互不干扰(锁/MVCC)。D持久性Durability：提交后永久保存即使崩溃Redo Log恢复。BEGIN/START TRANSACTION开启 COMMIT提交 ROLLBACK回滚 SAVEPOINT设置回滚点。"),
    ("事务隔离级别？脏读/幻读/不可重复读？", "medium", "ANSI SQL-92定义四级隔离级别(从低到高)：Read Uncommitted读未提交(可能脏读Dirty Read读到未提交数据/不可重复读Non-Repeatable Read/幻读Phantom Read)。Read Committed读已提交(Oracle/PostgreSQL/SQL Server默认 防脏读 但可能不可重复读和幻读 MVCC每次语句生成新快照)。Repeatable Read可重复读(MySQL InnoDB默认 防脏读和不可重复读 但可能MVCC间隙锁Gap Lock防幻读)。Serializable串行化(最高隔离 强制串行执行 性能最差 锁开销最大)。大多数OLTP应用RC足够。InnoDB RR通过MVCC+Next-Key Lock(Record+Gap)几乎等效Serial但性能好很多。"),
    ("MVCC多版本并发控制原理？InnoDB实现？", "medium", "MVCC Multi-Version Concurrency Control：通过维护数据多个版本(Version Chain)实现读写不冲突(读不加共享锁 读快照Snapshot)。InnoDB实现核心：Undo Log回滚日志存储旧版本数据形成版本链(roll_ptr指针指向undo log)。Read View读视图判断版本可见性(包含min_trx_id最小活跃事务ID/max_trx_id最大事务ID/m_ids列表当前活跃事务IDs)。RC级别：每条SELECT语句生成新Read View(能看到本语句启动后已提交事务更新)。RR级别：事务第一条SELECT生成Read View后续复用(只能看到事务启动前已提交数据)。优点：读写不冲突无锁高并发。缺点：额外存储空间(Undo Log膨胀需purge线程清理)、需要回滚旧版本行数多时扫描慢。"),
    ("MySQL索引原理？B+树？聚簇索引Clustered Index？", "hard", "InnoDB引擎索引基于B+ Tree(平衡多路搜索树变种)：非叶子节点不存储Data只存Key+Pointer(扇出Fan Out高 层数Level少 通常3层即可存千万级数据 磁盘IO少)。叶子节点Leaf Node：聚簇索引(Clustered Index/主键索引 Primary Key)叶子节点存储完整数据行(Data Row)即数据即索引(表数据按主键B+树组织)。二级索引Secondary Index(普通索引/非聚簇索引 Non-Clustered Index)叶子节点存储主键值(Primary Key Value)需要回表Table Lookup(Back to Clustered Index)获取完整行(覆盖索引Covering Index可避免回表提升性能)。B+树特点：范围查询Range Query优秀(叶子节点双向链表Double Linked List有序遍历)、查询稳定O(log n)。联合索引Composite Index遵循最左前缀Leftmost Prefix原则(如idx(a,b,c) 可查a/ab/abc不能单独b/c/ac/bc)。索引选择性Selectivity越高( distinct/count ratio接近1)效果越好。"),
    ("MySQL索引优化？Explain执行计划分析？", "medium", "Explain关键字段解读优化方向：type访问类型(从优到差 system>const>eq_ref>ref>range>index>ALL 全表扫描ALL需优化建索引)。key实际使用的索引名( NULL表示没用索引 possible_keys显示可能用到的索引)。rows预估扫描行数(越小越好)。Extra重要提示(Using filesort文件排序需优化排序Using temporary临时表需优化分组 Using index covering index覆盖索引好 Using index condition pushdown ICP索引条件下推好 Using where回表后过滤 Backward index scan逆序扫描)。优化手段：合理建索引(高选择性列/WHERE ORDER BY GROUP BY JOIN ON列)、避免SELECT *(用具体字段利用覆盖索引)、避免索引失效(函数计算/隐式转换/LIKE '%xx'/OR/NOT IN/IS NULL左列)、深分页优化(延迟关联Deferred Join/游标Cursor/书签Bookmark/覆盖索引+JOIN)。SHOW PROFILE查看各阶段耗时。Optimizer Trace深入理解优化器决策过程。"),
    ("MySQL锁机制？行锁Row Lock/表锁Table Lock/意向锁Intention Lock？", "medium", "InnoDB锁粒度：行级锁Row-Level Lock(粒度最小并发度高但开销大)：Record Lock精确锁定索引记录行、Gap Lock间隙锁(锁索引记录间隙防插入Next-Key Lock=Record+Gap解决RR级别Phantom Read幻读问题)、Insert Intention Lock插入意向锁。表级锁Table-Level Lock：MDL Metadata Lock( DDL操作ALTER TABLE等获取表级元数据锁 阻止并发DML导致Waiting for table metadata lock常见线上故障)、意向锁Intention Lock( IS意向共享锁 IX意向意向锁 表级快速判断是否可加行锁 兼容性矩阵)。锁算法Lock Algorithm：Record Gap Next-key。死锁Deadlock检测( innodb_deadlock_detect=ON自动检测回滚代价小的事务)和超时等待( innodb_lock_wait_timeout默认50秒)。显式锁：SELECT ... FOR UPDATE(排他锁X锁) LOCK IN SHARE MODE(共享锁S锁)。乐观锁Optimistic Locking(版本号Version/时间戳Timestamp CAS更新) vs 悲观锁Pessimistic Locking(... FOR UPDATE)。"),
    ("SQL注入原理与防护？Parameterized Query？", "easy", "SQL Injection漏洞本质：将用户输入直接拼接到SQL语句字符串中执行导致语句结构被恶意改变(Union注入/布尔盲注/时间盲注/报错注入)。经典Payload：' OR '1'='1 --。危害：数据泄露/篡改/删除/提权( xp_cmdshell)。防护黄金法则：永远使用参数化查询PreparedStatement(占位符?驱动程序负责转义特殊字符和类型检查)！ORM框架Hibernate/MyBatis自动参数化( MyBatis中#{}是参数化 ${}是字符串拼接极其危险禁止用于用户输入！)。其他防线：输入验证Input Validation(白名单Whitelist优于黑名单Blacklist)、最小权限Principle of Least Privilege(应用数据库账号不给DROP GRANT FILE等高危权限)、WAF Web Application Firewall辅助检测拦截异常SQL特征模式。存储过程Stored Procedure相对安全但仍需参数化。"),
    ("MySQL主从复制Replication原理？异步/半同步/组复制MGR？", "medium", "主从复制Master-Slave Replication核心目的：读写分离Read-Write Splitting分担读压力 + 数据备份容灾 + 离线分析不影响主库。原理：Master主库开启binlog(二进制日志 记录所有数据变更DDL DML Statement Row Mixed格式) -> Slave从库IO Thread I/O线程拉取Master binlog写入本地Relay Log中继日志 -> Slave SQL Thread SQL线程重放Relay Log中的事件应用到本地实现数据同步。三种模式：异步复制Asynchronous Replication(默认 Master写完binlog即返回给客户端 不等待Slave确认 可能丢失最后几条事务数据)。半同步Semi-Synchronous Replication( Master等待至少一个Slave收到Relay Log并ACK确认后才返回客户端 commit latency增加1 RTT但数据更安全 loss window缩小)。组复制Group Replication MGR MySQL 5.7+(基于Paxos分布式共识协议 单主Single-Primary或多主Multi-Primary模式 基于certification-based replication 强数据一致性 几乎无数据丢失)。GTID Global Transaction Identifier替代传统file-position binlog定位( UUID:transaction_id 格式全局唯一 便于故障转移Failover)。延迟Replication Lag监控Seconds_Behind_Master(主从延迟秒数)过大原因：Slave硬件差/大事务/长查询/网络抖动/磁盘IO瓶颈。解决方案：并行复制( MTS Multi-Threaded Slave Database Parallel Replication LOGICAL_CLOCK based/ WRITE_SET based based on group commit)、SSD加速、大事务拆分。"),
    ("Redis数据结构与应用场景？String/Hash/List/Set/ZSet？", "easy", "Redis五大基本数据结构及应用：String字符串(简单KV缓存/计数器INCR/DECR原子操作/分布式锁SETNX EX PX/限流滑动窗口)。Hash哈希(对象属性存储如用户信息Profile field-value对 节省内存比String多个key少一次序列化)。List列表( LPUSH RPUSH LPOP RPOP 消息队列简单实现/最新列表 LPUSH + LTRIM保留最近N条/栈队列)。Set集合( SADD SMEMBERS SUNION SINTER SDIFF 去重/共同好友交集/标签系统/随机成员SRANDMEMBER抽奖)。ZSet有序集合Sorted Set( ZADD ZRANGE ZREVRANGE ZRANGEBYSCORE ZREM 排行榜Leaderboard/加权随机/范围查询/延时队列)。高级数据结构：HyperLogLog基数统计( PFADD PFCOUNT UV去重 12KB内存误差0.81% Bitmap位图( SETBIT GETBIT BITCOUNT BITOP 签到/用户在线状态 Bloom Filter布隆过滤器)。Stream流( XADD XREADGROUP XACK 消息队列5.0+ Consumer Group消费组)。Geospatial地理位置( GEOADD GEORADIUS GEODIST 附近的人/地点)。Bitmap位图( SETBIT GETBIT 统计)。"),
    ("Redis持久化？RDB vs AOF？混合持久化Hybrid Persistence？", "medium", "Redis两种持久化机制保障重启后数据恢复：RDB Redis DataBase Snapshot(快照)：fork()子进程在某个时刻将内存数据集快照dump到磁盘.rdb文件(二进制紧凑压缩 体积小 恢复速度快save 900 1/save 300 10/save 60 10000触发)。缺点：可能丢失最后一次快照后数据( fork耗时大内存阻塞/ Copy-On-Write内存额外开销)、不支持增量备份。AOF Append Only File(追加 only 文件)：记录每条写命令(文本协议可读性好)追加到appendonly.aof文件。fsync策略appendfsync always(每秒fsync最多丢1秒数据)/everysec(每次写入fsync最安全但性能差)/no(交由OS)。缺点：文件体积远大于RDB、恢复速度慢(需重放所有命令)、AOF Rewrite重写压缩( bgrewriteaof后台fork子进程压缩去冗余命令)。混合持久化Hybrid Persistence(Redis 4.0+默认开启)：RDB头部(基础全量数据体积小恢复快) + AOF尾部(增量新命令) 兼顾体积和安全性。恢复时先加载RDB再重放AOF。生产环境建议RDB+AOF+主从+哨兵/集群多层保障。"),
    ("Redis高可用？哨兵Sentinel vs 集群Cluster？", "medium", "Redis高可用演进：主从复制Master-Slave(异步复制 数据冗余读扩展 但手动故障转移Failover复杂且可能丢失数据)。哨兵模式Sentinel( 2.8+ 自动故障转移Failover 核心三个功能Monitoring监控(心跳PING Sentinel <-> Redis Master/Slave)、Notification通知(故障转移通过Script通知管理员)、Automatic Failover自动故障转移(SDown主观宕机->ODown客观宕机(quorum多数派)->Vote选举Leader Sentinel->Promote Slave为新的Master->Reconfig other Slaves指向New Master->Notify Clients)。Sentinel节点本身也是分布式(奇数个>=3防Split Brain脑裂)。集群模式Cluster( 3.0+ 数据分片Sharding + 高可用 去中心化 无Proxy直连)：16384个Hash Slot槽位( CRC16(key)%16384 分配到各Master节点) -> Master-Slave主从(每个Master有Slave副本) -> Gossip Protocol八卦协议传播集群状态( Ping/Pong/Fail/Publish ) -> MOVED/ASK重定向(客户端路由到正确节点)。Cluster限制：多Key操作( MGET/MSET/SINTER等)必须在同一Slot( hashtag{}强制)、不支持多数据库空间(DB0 only)、事务有限制( Multi/Exec涉及多Key同Slot)、Pipeline支持受限。选型：数据量<单机内存上限用Sentinel够用；数据量大需水平扩展用Cluster。Proxy模式( Twemproxy/Codis/ predixy)中间件屏蔽集群细节兼容原Redis协议但引入额外延迟和单点。"),
    ("Redis缓存穿透/击穿/雪崩？解决方案？", "medium", "三大缓存异常问题及对策：缓存缓存穿透Cache Penetration(查询一定不存在的数据如ID=-1 每次都穿透到DB)：①布隆过滤器Bloom Filter( Redis RedisBloom模块或Guava本地 过滤绝对不存在的key 零漏判有一定误判率可接受) ②缓存空值null(短TTL 30s~5min 防止频繁打DB 但浪费内存存无效数据)。缓存击穿Cache Breakdown(热点Key突然过期瞬间大量并发请求打到DB)：①互斥锁Mutex Lock( SETNX分布式锁 只让一个线程重建缓存 其他线程Sleep重试 保证一致性但吞吐下降) ②逻辑过期Logical Expiration(不设真实TTL 字段存逻辑过期时间 异步后台重建缓存 返回可能过期数据但高吞吐)。③热点数据永不过期(定时异步后台主动刷新)。缓存雪崩Cache Avalanche(大量Key同时过期或Redis宕机导致DB压力暴增)：①TTL加随机值Random TTL( base + random(0, max) 打散过期时间) ②多级缓存L1 Local(Caffeine/Guava) + L2 Distributed(Redis) ③熔断降级Circuit Breaker( 返回默认兜底数据/友好提示 保护DB不被压垮) ④限流Rate Limiting(前端+网关+Nginx+Redis Lua多级限流) ⑤Redis高可用( Sentinel/Cluster防单点故障)。综合采用多层纵深Defense in Depth策略。"),
    ("MongoDB文档数据库特点？BSON？副本集？分片？", "medium", "MongoDB NoSQL Document-Oriented Database文档数据库特点：1.灵活Schema(无需预定义表结构 同一字段不同文档可有不同类型/缺失 新增字段只需插入即可无需ALTER TABLE) 2.嵌套文档Nested Documents/数组Arrays(减少JOIN关联查询 应用代码方便) 3.丰富的查询语言(索引Index/聚合管道Aggregation Pipeline/地理空间Geospatial/全文检索Text Search) 4.水平扩展Sharding(自动数据均衡) 5.副本集Replica Set(自动故障转移High Availability)。数据格式BSON(Binary JSON)：二进制JSON扩展 支持更多Date/Binary/ObjectId/Timestamp等原生类型 比纯文本JSON更高效(长度前缀Type Byte)。ObjectId：12字节唯一标识符(4字节timestamp + 3字节machine identifier + 2字节process id + 3字节counter 自增可近似提取时间)。副本集Replica Set架构：Primary主节点(读写) + Secondary从节点(只读可配置) + Arbiter仲裁节点(仅投票无数据 防止偶数节点平票)。Oplog(Operation Log capped collection固定大小集合)复制到从节点异步最终一致Eventual Consistency。读偏好Read Preference( primaryPreferred/secondaryPreferred/nearest)。写关注Write Concern( w majority/journal/majority确认数)。分片Sharding：Chunk数据块(默认64MB) + Shard Key分片键(基数高Cardinality/分布均匀Distribution/查询常用Query Pattern至关重要) + Shard节点( Mongos路由服务器 + Config Server配置服务器元数据存储 + Shard存储节点)。分片策略Range范围/Hash哈希(更均匀)。均衡器Balancer后台进程迁移Chunk(迁移期间有性能影响)。Jumbo Chunk超大块需手动split拆分。"),
    ("PostgreSQL vs MySQL？PG优势场景？MVCC差异？", "medium", "PostgreSQL号称世界上最先进的开源数据库The World's Most Advanced Open Source Relational Database Object-Relational DBMS ORDBMS：优势1.SQL标准合规性极高(SQL:2011支持度最高) 2.复杂查询优化能力强(窗口函数Window Function/CTE Common Table Expression WITH RECURSIVE递归查询/JSONB JSON二进制存储查询/GiST GIN BRIN丰富索引类型/ FDW Foreign Data Wrapper外部数据包装器访问异构数据源) 3.可靠性极高( Write-Ahead Logging WAL预写日志 PITR Point-in-Time Recovery时间点恢复/ Hot Standby热备流复制 Logical Decoding逻辑解码CDC Change Data Capture pgoutput plugin) 4.扩展性极强(PostGIS地理空间扩展/pg_vector向量相似度搜索AI/ Citus分布式扩展/hstore/ltree等)。劣势：学习曲线陡峭/生态工具不如MySQL丰富( ORM/运维监控)/简单CRUD性能略低/更新大表需要表重写Rewrite Table( VACUUM FULL清理死亡元组回收空间 PG特色操作 需要额外磁盘空间和IO)。MVCC实现差异：InnoDB( Update-in-Place原地更新+ Undo Log旧版本 多版本共存 Roll_ptr指针链) vs PostgreSQL(Append-Only新版本写到新位置 Old/New版本共存 旧版本需VACUUM清理否则表膨胀bloat PG特色操作需定期autovacuum或手动vacuum)。事务隔离：PG的Repeatable Read真正基于快照Snapshot Isolation( Serializable级别在PG 9.1+也是基于SSI SSI Serializable Snapshot Isolation快照隔离实现 并非真正串行化 性能更好)。适用场景：复杂查询分析/ GIS地理信息系统/ 科学数据/ JSON文档/ 需要严格ACID和复杂约束的企业应用。MySQL适合简单CRUD/Web应用/电商/读多写少。两者互补共存。"),
    ("数据库索引设计原则？什么不该建索引？", "medium", "索引设计黄金原则：1.WHERE/ORDER BY/GROUP BY/JOIN ON条件列(最常用查询条件优先) 2.高选择性High Selectivity列( distinct/count ratio越接近1越好 如UUID/手机号/邮箱 性别/布尔等低选择性列单独建索引意义不大除非复合索引前导列) 3.区分度Distinctiveness高的列优先放在联合索引前面(最左前缀原则 Leftmost Prefix) 4.覆盖索引Covering Index( SELECT列全部包含在索引中 避免回表Back to Table Lookup 大幅提升性能 Extra: Using index) 5.小表Small Table(行数<几千) 全表扫描Sequential Scan可能比索引更快(随机IO vs 顺序IO) 不值得建索引。不该建索引的情况：①表中数据量很小(全表扫描更快) ②很少作为查询条件的列(浪费存储和维护开销) ③频繁大批量INSERT/UPDATE/DELETE的列(索引维护拖慢写入 B+树分裂合并页Page Split/Merge开销) ④区分度极低的列(如性别男/女 索引选择性太差 Cardinality低) ⑤长文本列(如TEXT/BLOB 直接索引占用巨大 考虑前缀索引Prefix Index或全文索引Full-text Index)。复合索引列顺序原则：等值查询Equality列在前、范围查询Range列在后、经常一起出现的列放一起。索引不是越多越好(占用磁盘空间/降低写入性能/优化器选择困难) 定期分析unused indexes无用索引删除。EXPLAIN ANALYZE实测验证效果。"),
    ("数据库连接池Connection Pool原理与调优？", "medium", "连接池Purpose：数据库连接TCP三次握手+TLS认证开销大(数十毫秒级) 预先创建一批连接复用Reuse避免频繁建立Destroy和释放Release( Close归还池中而非真断开)。核心组件：空闲连接队列Idle Queue(等待被借用)、活跃连接Active Set(正在被使用中)、最大连接数Max Active(上限防止库被打爆)、最小空闲Min Idle(保底预热)、连接有效性校验Validation Query( borrow时ping/testOnBorrow/onReturn防止连接已被DB端关闭变成僵尸连接Stale Connection)、超时驱逐Eviction( timeBetweenEvictionRunsMillis检查间隔 minEvictableIdleTimeMillis空闲超时回收)、借出等待超时borrow timeout(排队Queue满时抛出异常或阻塞Wait)、泄漏检测Remove Abandoned(连接借出太久未归还视为泄漏强行回收 removeAbandoned=true)。主流连接池：HikariCP( Spring Boot 2.x默认 号称最快 lightweight 代码精良约130KB)、Druid(阿里巴巴 监控统计SQL FireWall防SQL注入功能强大)、C3P0(老牌较重)、Vibur(基于Java NIO异步)。调优建议：maximumPoolSize=(CPU核心数 * 2) ~ (CPU核心数 * 4)左右 根据压测实际QPS调整(观察Active峰值)。connectionTimeout连接超时( ms 借不到抛异常别让线程无限等)。idleTimeout/maxLifetime( MySQL默认wait_timeout 8h interactive_timeout 8h 连接超过此时间会被MySQL服务端断开 导致池中有僵尸连接 必须maxLifetime < MySQL wait_timeout 建议30min或更短 leakDetectionThreshold泄漏检测阈值。监控指标：active/idle/pending/waiting/total connections。"),
    ("数据库容量规划Capacity Planning？估算方法？", "medium", "容量规划目标：提前预测未来N个月/年的数据量和资源需求 避免线上故障(磁盘满/性能下降)。估算公式：单行平均大小Avg Row Size(字节) * 预估总行数Estimated Total Rows + 索引空间Index Space(约占数据量20%~50%视索引数量和类型而定) + 预留增长空间Headroom(50%~100%应对突发增长和碎片)。示例：订单表Order( 200 bytes/row * 1000万 orders = 2GB data + 1GB index ≈ 3GB total)。年增长率Yearly Growth Rate(如200%)推算未来所需空间。监控工具：information_schema.TABLES( data_length+index_length 查看各表大小)、SHOW TABLE STATUS、pt-disk-PostgreSQL pg_stat_user_tables/nodestats。告警阈值：磁盘使用率Disk Usage > 70%预警Warning > 85%紧急Critical > 95%致命Fatal(可能导致MySQL Crash无法启动InnoDB Recovery耗时极长)。扩容方案：垂直Scale Up(升级硬件CPU/内存/SSD NVMe RAID10 快速但天花板) vs 水平Scale Out(分库分表Sharding 复杂但理论上无限)。单表建议：< 2000万行( MySQL InnoDB) 或 < 单机物理内存Physical RAM能装下Hot Data热数据( Buffer Pool) 否则查询性能急剧下降(大量磁盘IO Random IO)。冷热数据分离Cold-Hot Data Separation(历史数据归档Archive到对象存储OSS/S3或冷存储库)。定期清理Delete过期数据(软删除Soft Delete标记+异步物理清理Job)。"),
]

for i, (t, d, a) in enumerate(db_qs):
    all_new_questions.append({'id':f'db-{i+1}','title':t,'category':'database','difficulty':d,'content':a[:150],'answer':a,'sourceType':'builtin','source':'数据库面试题','tags':['数据库']})

print(f"Network: {len(net_qs)}")
print(f"Database: {len(db_qs)}")

with open('temp_new_questions.json', 'w', encoding='utf-8') as f:
    json.dump(all_new_questions, f, ensure_ascii=False, indent=2)
    
print(f"Total prepared: {len(all_new_questions)}")
